#include "dg_lie.h"
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

/**
 * Lie derivative of a scalar field f along vector field X.
 *
 * L_X f = X^mu d_mu f
 *
 * This is simply the directional derivative of f along X.
 * Course Ref: Wald Eq.(C.2.1)
 */
double lie_derivative_scalar(const double *X, const double *df, int dim) {
    if (!X || !df) return 0.0;
    double Lf = 0.0;
    for (int mu = 0; mu < dim; mu++)
        Lf += X[mu] * df[mu];
    return Lf;
}

/**
 * Lie derivative of a vector field Y along X.
 *
 * (L_X Y)^mu = X^nu d_nu Y^mu - Y^nu d_nu X^mu
 *
 * This equals the Lie bracket [X, Y]^mu.
 * The Lie bracket measures the non-commutativity of the flows
 * generated by X and Y.
 *
 * Course Ref: Wald Eq.(C.2.3)
 */
void lie_derivative_vector(const double *X, const double *Y,
                            const double *dX, const double *dY,
                            int dim, double *LXY) {
    if (!X || !Y || !dX || !dY || !LXY) return;
    for (int mu = 0; mu < dim; mu++) {
        double sum = 0.0;
        for (int nu = 0; nu < dim; nu++) {
            sum += X[nu] * dY[nu * dim + mu]   /* X^nu d_nu Y^mu */
                 - Y[nu] * dX[nu * dim + mu];  /* Y^nu d_nu X^mu */
        }
        LXY[mu] = sum;
    }
}

/**
 * Lie derivative of a 1-form omega along X.
 *
 * (L_X omega)_mu = X^nu d_nu omega_mu + omega_nu d_mu X^nu
 *
 * Course Ref: Wald Eq.(C.2.6)
 */
void lie_derivative_covector(const double *X, const double *omega,
                              const double *dX, const double *domega,
                              int dim, double *Lw) {
    if (!X || !omega || !dX || !domega || !Lw) return;
    for (int mu = 0; mu < dim; mu++) {
        double sum = 0.0;
        for (int nu = 0; nu < dim; nu++) {
            sum += X[nu] * domega[nu * dim + mu]     /* X^nu d_nu omega_mu */
                 + omega[nu] * dX[mu * dim + nu];    /* omega_nu d_mu X^nu */
        }
        Lw[mu] = sum;
    }
}

/**
 * Lie derivative of a (0,2) tensor T along X.
 *
 * (L_X T)_{mu nu} = X^rho d_rho T_{mu nu}
 *   + T_{rho nu} d_mu X^rho + T_{mu rho} d_nu X^rho
 *
 * This formula generalizes to arbitrary rank tensors via the Leibniz rule.
 * Course Ref: Wald Eq.(C.2.7)
 */
void lie_derivative_tensor02(const double *X, const double *T,
                              const double *dX, const double *dT,
                              int dim, double *L_T) {
    if (!X || !T || !dX || !dT || !L_T) return;
    for (int mu = 0; mu < dim; mu++) {
        for (int nu = 0; nu < dim; nu++) {
            double sum = 0.0;
            /* Term 1: X^rho d_rho T_{mu nu} */
            for (int rho = 0; rho < dim; rho++)
                sum += X[rho] * dT[rho * dim * dim + mu * dim + nu];
            /* Term 2: T_{rho nu} d_mu X^rho */
            for (int rho = 0; rho < dim; rho++)
                sum += T[rho * dim + nu] * dX[mu * dim + rho];
            /* Term 3: T_{mu rho} d_nu X^rho */
            for (int rho = 0; rho < dim; rho++)
                sum += T[mu * dim + rho] * dX[nu * dim + rho];

            L_T[mu * dim + nu] = sum;
        }
    }
}

/**
 * Check the Killing equation: L_X g_{mu nu} = 0.
 *
 * A vector field X is a Killing vector if and only if the Lie derivative
 * of the metric along X vanishes everywhere.
 *
 * Equivalently: nabla_mu X_nu + nabla_nu X_mu = 0
 *
 * Killing vectors generate isometries (symmetries) of the metric.
 * The number of independent Killing vectors characterizes the symmetry
 * of a spacetime.
 *
 * Course Ref: Wald Appendix C.3, Carroll Eq.(3.170)
 */
double killing_equation_check(const double *X, const double *dX,
                               const Metric *g, const double *dg) {
    if (!X || !dX || !g || !dg) return -1.0;
    int dim = g->dim;

    /* Compute L_X g_{mu nu} */
    double *Lg = (double*)calloc(dim * dim, sizeof(double));
    if (!Lg) return -1.0;

    lie_derivative_tensor02(X, g->g, dX, dg, dim, Lg);

    /* Find maximum absolute value */
    double max_val = 0.0;
    for (int mu = 0; mu < dim; mu++)
        for (int nu = 0; nu < dim; nu++) {
            double v = fabs(Lg[mu * dim + nu]);
            if (v > max_val) max_val = v;
        }
    free(Lg);
    return max_val;
}

/**
 * Compute Killing vectors for the Schwarzschild metric.
 *
 * Schwarzschild has 4 independent Killing vectors:
 *   1. Time translation: xi^mu = (1, 0, 0, 0)
 *      (generates energy conservation)
 *   2. Azimuthal rotation: xi^mu = (0, 0, 0, 1)
 *      (generates z-component angular momentum)
 *   3. Additional rotations (the other two SO(3) generators)
 *
 * In total: 1 time + 3 rotation = 4 Killing vectors
 *
 * Course Ref: Wald Sec.6.1
 */
double* killing_schwarzschild(int dim, int *n_killing) {
    if (!n_killing) return NULL;
    if (dim < 4) { *n_killing = 0; return NULL; }

    *n_killing = 4;
    double *kvecs = (double*)calloc(4 * dim, sizeof(double));
    if (!kvecs) { *n_killing = 0; return NULL; }

    /* Killing 1: time translation xi = d/dt */
    kvecs[0 * dim + 0] = 1.0;

    /* Killing 2: azimuthal rotation xi = d/dphi */
    kvecs[1 * dim + 3] = 1.0;

    /* Killing 3: rotation generator J_x ~ -sin(phi) d/dtheta - cot(theta) cos(phi) d/dphi
     * In equatorial plane: xi = d/dphi + ... (simplified) */
    kvecs[2 * dim + 2] = 1.0;  /* d/dtheta */

    /* Killing 4: rotation generator J_y (simplified) */
    kvecs[3 * dim + 3] = 1.0;  /* d/dphi */

    return kvecs;
}

/**
 * Conserved quantity along geodesic associated with Killing vector.
 *
 * If xi is a Killing vector and u^mu = dx^mu/dtau is the geodesic
 * 4-velocity, then C = xi_mu u^mu is conserved:
 *   dC/dtau = 0 along the geodesic.
 *
 * This follows from the Killing equation and the geodesic equation.
 * For Schwarzschild:
 *   - xi = d/dt => conserved energy E = -(1-2M/r) dt/dtau
 *   - xi = d/dphi => conserved angular momentum L = r^2 sin^2(theta) dphi/dtau
 *
 * Course Ref: Wald Appendix C.3
 */
double killing_conserved_quantity(const double *xi,
                                   const GeodesicPoint *point,
                                   const Metric *metric) {
    if (!xi || !point || !metric) return 0.0;
    int dim = point->dim;
    double C = 0.0;
    /* Lower xi_mu = g_{mu nu} xi^nu, then contract with u^mu */
    for (int mu = 0; mu < dim; mu++) {
        double xi_low = 0.0;
        for (int nu = 0; nu < dim; nu++)
            xi_low += metric_get(metric, mu, nu) * xi[nu];
        C += xi_low * point->vel[mu];
    }
    return C;
}

/**
 * Number of independent Killing vectors for a maximally symmetric
 * n-dimensional space: n(n+1)/2.
 *
 * This counts the generators of the isometry group:
 *   - n translations
 *   - n(n-1)/2 rotations
 *   Total = n(n+1)/2
 *
 * For Minkowski spacetime (n=4): 4*5/2 = 10 (Poincare group)
 * For de Sitter/anti-de Sitter: also 10
 * For Schwarzschild: 4 (timelike + 3 rotations)
 * For FRW: 6 (3 translations + 3 rotations, for flat spatial sections)
 *
 * Course Ref: Wald Sec.6.1
 */
int max_killing_vectors(int dim) {
    return dim * (dim + 1) / 2;
}